### ISSUE TITLE
haxe 3.4 issue

### ISSUE THREAD

**Issue by francescoagati** [back2dos/js-virtual-dom#2]
Hi,
i am testing hxx with with virtual dom.
with this code 
```
    var x = vdom.VDom.hxx('    
      <div>
          <div class="foo">2</div>
      </div>
    ');
    trace(x);
```

i get src/Main.hx:8: characters 11-14 : Unknown identifier : div

you can find the code example here https://github.com/francescoagati/js-virtual-dom/blob/master/src/Main.hx

**Comment by back2dos** [comment]
That is the correct behavior. You need to `import vdom.VDom.*` for `div` to come into scope.

**Comment by francescoagati** [comment]
works thanks :-)
